ALARM_NAIVE_SEQ_LEN = 4
ALARM_NAIVE_THRESHOLD_SMOKE = 16
ALARM_NAIVE_THRESHOLD_PM025 = 128
ALARM_NAIVE_THRESHOLD_VOC = 32
ALARM_NAIVE_THRESHOLD_HUMID = 4  # bi-directional
ALARM_INDICATE_VAL = 256
ALARM_NAIVE_BG_LR = 1e-4
HUMIDITY_SUPPRESSION = 64
