ALARM_NAIVE_SEQ_LEN = 4
ALARM_NAIVE_THRESHOLD_SMOKE = 8
ALARM_NAIVE_THRESHOLD_PM025 = 128
ALARM_NAIVE_THRESHOLD_VOC = 128
ALARM_NAIVE_THRESHOLD_HUMID = 8  # bi-directional
ALARM_INDICATE_VAL = 1024
ALARM_NAIVE_BG_LR = 1e-4
